### ISSUE TITLE
Search bar bug: Maximum Update depth exceeded

### ISSUE THREAD

**Issue by AlexHooperDev** [Flare-code/flare-dashboard#14]
I've noticed that on the inventory page, we seem to be getting a browser error relating to the search bar. Are you able to look into this?
![Screenshot 2022-11-10 at 13 38 07](https://user-images.githubusercontent.com/65167725/201106537-5a46963c-b696-4f32-b18f-0f0bdf35f425.png)

**Comment by JEFFKAY16** [comment]
Hey @AlexHooperDev - I'll jump on it right away
